# Generated by Django 5.2.12 on 2026-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_freelance_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
