# Generated by Django 5.2.12 on 2026-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_profile_image_alter_freelance_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='freelances/'),
        ),
    ]
