# Generated by Django 5.2.12 on 2026-09-09 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_criar_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portfolios/')),
                ('titulo', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('link', models.URLField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
